name: develop

on:
  push:
    branches:
      - "feature/ci_build"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      build-app-kind: "CLI, WPF, Xamarin.Mac"
      build-configuration: Debug
